import { writeFileSync, mkdirSync } from "node:fs";
import type {
  Persona,
  DateRecord,
  DemoData,
  Signal,
} from "../src/lib/persona/schema";
import { rankAll } from "../src/lib/matching/ranking";
import {
  roundRobin,
  curveballFor,
  pairHash,
} from "../src/lib/matching/roundRobin";
import { scoreCandidate } from "../src/lib/matching/compatibility";
const cast = [
  [
    "Maya Chen",
    "Product designer · maker of small, useful things",
    "Design",
    "Photography",
    "Coffee",
    "A sketchbook in every bag. A plan with plenty of room for a detour.",
    "Making things people actually use",
    "A coffee walk that accidentally becomes a photo walk",
    64,
    76,
    78,
    93,
    35,
    72,
  ],
  [
    "Arjun Rao",
    "Software engineer · weekend trail collector",
    "Building things",
    "Outdoors",
    "Cooking",
    "Builder energy. Trail shoes by the door. One very overthought dinner recipe.",
    "Tiny tools and big mountain routes",
    "A farmers market, then making something from whatever looks good",
    48,
    56,
    92,
    85,
    65,
    80,
  ],
  [
    "Nina Brooks",
    "Creative director · amateur record-store archaeologist",
    "Design",
    "Music",
    "Art",
    "Excellent taste. A slightly unreasonable number of records.",
    "Why some design feels like a song",
    "A record shop, followed by a very opinionated playlist swap",
    78,
    73,
    70,
    90,
    40,
    60,
  ],
  [
    "Leo Martins",
    "Indie developer · excellent at side quests",
    "Games",
    "Building things",
    "Coffee",
    "Will build the app. Will also turn choosing lunch into a side quest.",
    "Games that make you think differently",
    "A board-game café with no strict end time",
    65,
    88,
    75,
    95,
    25,
    66,
  ],
  [
    "Zara Patel",
    "Community builder · good at making strangers feel at home",
    "Community",
    "Cooking",
    "Reading",
    "The friend who turns “a few people” into a dinner table of twelve.",
    "What makes a city feel like home",
    "A neighborhood market and a shared snack",
    92,
    65,
    68,
    82,
    47,
    62,
  ],
  [
    "Jules Park",
    "Photographer · collector of little observations",
    "Photography",
    "Travel",
    "Art",
    "Finds the interesting corner. Usually stays there a little longer.",
    "The stories just outside the frame",
    "A gallery visit with a slow walk afterward",
    44,
    82,
    60,
    94,
    30,
    86,
  ],
  [
    "Sofia Reyes",
    "Tech educator · learning out loud",
    "Learning",
    "Writing",
    "Music",
    "Makes complicated things feel simple. Has questions about everything else.",
    "The thing you recently changed your mind about",
    "A bookshop browse and swapping one recommendation each",
    76,
    52,
    84,
    96,
    61,
    48,
  ],
  [
    "Theo Wilson",
    "Climate-tech maker · urban garden enthusiast",
    "Building things",
    "Outdoors",
    "Cooking",
    "Big project energy, small balcony garden. Somehow both are thriving.",
    "How to make cities a little more livable",
    "A botanical garden and a very good sandwich",
    54,
    43,
    90,
    83,
    72,
    64,
  ],
  [
    "Isha Kapoor",
    "Brand designer · likely to redesign the menu",
    "Design",
    "Art",
    "Travel",
    "Notices every tiny detail. Still happy to get a little lost.",
    "The story a brand tells before it says anything",
    "An art walk with an unplanned last stop",
    70,
    85,
    77,
    91,
    28,
    87,
  ],
  [
    "Owen Ellis",
    "Startup operator · Sunday cyclist",
    "Outdoors",
    "Coffee",
    "Reading",
    "A calendar with breathing room. A cycling route without a finish line.",
    "Making a little time go a long way",
    "A gentle bike ride and a bakery stop",
    49,
    35,
    85,
    75,
    85,
    60,
  ],
  [
    "Amara Okafor",
    "Writer · keeper of the good questions",
    "Writing",
    "Reading",
    "Art",
    "Quiet observations, excellent questions. A conversation you forget to check your phone in.",
    "The book that stayed with you",
    "A bookshop with a café upstairs",
    38,
    48,
    72,
    94,
    68,
    45,
  ],
  [
    "Kai Nakamura",
    "Creative coder · curious about everything analog",
    "Building things",
    "Music",
    "Photography",
    "Digital projects. Analog hobbies. Very committed to the experiment.",
    "Where code meets the physical world",
    "An interactive exhibition, then sketching ridiculous inventions",
    61,
    81,
    83,
    97,
    31,
    70,
  ],
  [
    "Priya Nair",
    "Product lead · running before the city wakes up",
    "Running",
    "Cooking",
    "Community",
    "Clear head, good questions, alarm clock doing the heavy lifting.",
    "Building a team that actually enjoys the work",
    "A park walk after a relaxed brunch",
    72,
    38,
    93,
    80,
    88,
    57,
  ],
  [
    "Ben Carter",
    "Illustrator · aspiring excellent baker",
    "Art",
    "Cooking",
    "Games",
    "Makes a little mess. Usually turns it into something worth keeping.",
    "Making something just for the fun of it",
    "A low-stakes baking experiment",
    57,
    65,
    61,
    87,
    52,
    49,
  ],
  [
    "Elena Rossi",
    "Experience designer · museum wanderer",
    "Design",
    "Art",
    "Reading",
    "An entire afternoon disappears in the right museum.",
    "Why places change the way we feel",
    "A small museum and a big conversation",
    52,
    55,
    75,
    93,
    58,
    64,
  ],
  [
    "Dev Shah",
    "Founder · coffee-powered tinkerer",
    "Building things",
    "Coffee",
    "Games",
    "Has a prototype for that. Might need a reminder to take a break.",
    "Ideas small enough to actually ship",
    "A café and inventing a wonderfully unnecessary product",
    75,
    72,
    98,
    91,
    46,
    55,
  ],
  [
    "Ruby James",
    "Newsletter maker · live-music regular",
    "Writing",
    "Music",
    "Community",
    "A good story, a small gig, a room full of future friends.",
    "The people behind the things we love",
    "A small live show with time to talk before it starts",
    87,
    79,
    71,
    88,
    33,
    61,
  ],
  [
    "Rohan Mehta",
    "Data storyteller · weekend cook",
    "Building things",
    "Cooking",
    "Reading",
    "The spreadsheet is organized. The recipe is mostly a suggestion.",
    "The story hiding inside a pile of numbers",
    "A food market and finding one thing neither has tried",
    51,
    57,
    86,
    84,
    67,
    58,
  ],
  [
    "Luna Silva",
    "Architect · happiest somewhere outside",
    "Design",
    "Outdoors",
    "Photography",
    "Thinks in spaces. Recharges in wide-open ones.",
    "Buildings that feel like they belong",
    "A walking tour ending at the water",
    58,
    66,
    80,
    88,
    48,
    91,
  ],
  [
    "Miles Reed",
    "Audio engineer · record collector",
    "Music",
    "Games",
    "Coffee",
    "Good listener, better playlist. A very strong opinion on the speakers.",
    "What makes a song feel like a place",
    "A listening bar at a volume you can talk over",
    45,
    51,
    73,
    85,
    69,
    45,
  ],
  [
    "Aanya Das",
    "Researcher · recreational rabbit-hole enthusiast",
    "Learning",
    "Reading",
    "Outdoors",
    "One question, five tabs, and suddenly it is midnight.",
    "A question nobody has quite answered yet",
    "A science museum followed by a walk",
    41,
    46,
    87,
    99,
    74,
    67,
  ],
  [
    "Finn Taylor",
    "Motion designer · bad at sitting still",
    "Design",
    "Running",
    "Travel",
    "A little momentum makes everything better. Including the weekend.",
    "How movement changes a story",
    "A city wander with a new neighborhood as the destination",
    80,
    91,
    76,
    86,
    21,
    93,
  ],
  [
    "Tara Singh",
    "Social entrepreneur · dinner-party diplomat",
    "Community",
    "Cooking",
    "Writing",
    "Makes room at the table. Then asks a question everyone wants to answer.",
    "A small idea that helps real people",
    "Cooking something simple together with no competition",
    90,
    61,
    86,
    87,
    55,
    59,
  ],
  [
    "Noah Kim",
    "Game designer · amateur film photographer",
    "Games",
    "Photography",
    "Art",
    "Finds the rules interesting. Finds breaking them a little more interesting.",
    "Why play belongs in everyday life",
    "A photo scavenger hunt, with gloriously loose rules",
    67,
    84,
    79,
    96,
    30,
    78,
  ],
  [
    "Freya Ahmed",
    "Editor · slow-weekend specialist",
    "Reading",
    "Coffee",
    "Outdoors",
    "Less rush, more noticing. A good weekend needs very little scheduling.",
    "A sentence that changed the way you see things",
    "Coffee, then a long walk without a destination",
    43,
    41,
    64,
    86,
    80,
    63,
  ],
] as const;
const people: Persona[] = cast.map((row, i) => {
  const [
    name,
    headline,
    t1,
    t2,
    t3,
    read,
    topic,
    date,
    socialEnergy,
    spontaneity,
    ambitionPace,
    curiosity,
    routinePreference,
    adventurePreference,
  ] = row;
  const id = name.toLowerCase().split(" ")[0];
  const interests = [t1, t2, t3];
  const ev = [
    {
      id: "e1",
      source: "linkedin" as const,
      text: `${headline}. Interested in ${t1.toLowerCase()} and sharing useful ideas.`,
      context: "Authored fictional LinkedIn-style fixture",
    },
    {
      id: "e2",
      source: "instagram" as const,
      text: `A weekend with ${t2.toLowerCase()}, ${t3.toLowerCase()}, and a little time for something new.`,
      context: "Authored fictional Instagram-style fixture",
    },
    {
      id: "e3",
      source: "instagram" as const,
      text: `A favorite way to spend a free afternoon: ${date.toLowerCase()}.`,
      context: "Authored fictional caption fixture",
    },
  ];
  const signal = (label: string, evidenceIds: string[] = ["e2"]): Signal => ({
    label,
    confidence: 78 + (i % 4) * 3,
    evidenceIds,
  });
  return {
    id,
    name,
    headline,
    avatarUrl: `/avatars/${i + 1}.jpg`,
    fictional: true,
    analysisMode: "fixture",
    sources: { linkedinUrl: "", instagramUrl: "" },
    identityConfidence: 90 + (i % 9),
    identitySignals: [
      "Two authored source fixtures describe the same fictional character.",
      "This is a fictional demonstration, not a verified real-world identity.",
    ],
    needs: [
      signal(
        spontaneity > 65
          ? "Room for a little spontaneity"
          : "A pace with breathing room",
        ["e3"],
      ),
      signal("Curiosity that goes both ways", ["e1", "e2"]),
    ],
    hobbies: [signal(t2), signal(t3)],
    interests: interests.map((t, j) => signal(t, j === 0 ? ["e1"] : ["e2"])),
    values: [signal("Make space for learning", ["e1"])],
    conversationHooks: [signal(topic, ["e1", "e3"])],
    socialRhythm:
      socialEnergy > 70
        ? "In this fictional card, shared plans and meeting people seem energizing."
        : "In this fictional card, smaller plans and a little quiet time seem welcome.",
    communicationStyle:
      "Warm, curious, with a preference for specific questions over small talk.",
    datingRead: {
      socialEnergy,
      spontaneity,
      ambitionPace,
      curiosity,
      routinePreference,
      adventurePreference,
    },
    matchPreferences: {
      origin: "fictional",
      traits: [
        {
          dimension: "curiosity",
          desiredValue: 85 + (i % 3) * 5,
          importance: 0.35,
        },
        {
          dimension: "spontaneity",
          desiredValue: Math.round(40 + spontaneity * 0.4 + (i % 4) * 5),
          importance: 0.25,
        },
        {
          dimension: "socialEnergy",
          desiredValue: Math.round(35 + socialEnergy * 0.4),
          importance: 0.2,
        },
        {
          dimension: "ambitionPace",
          desiredValue: Math.round(45 + ambitionPace * 0.35),
          importance: 0.2,
        },
      ],
    },
    agent: {
      openingStyle: `Ask a warm question about ${t1.toLowerCase()}.`,
      conversationStyle:
        "Playful, attentive, short replies. Make space for a real answer.",
      likelyGoodTopics: interests,
      dateEnergy:
        socialEnergy > 65 ? "Bright & curious" : "Thoughtful & curious",
    },
    oneLineRead: read,
    twoHourTopic: topic,
    idealLowPressureDate: date,
    confidence: {
      overall: 80 + (i % 10),
      linkedin: 86 + (i % 9),
      instagram: 74 + (i % 14),
    },
    evidence: ev,
  };
});
const dates: DateRecord[] = roundRobin(
  people.map((p) => p.id),
  5,
).map(({ round, a, b }, index) => {
  const p = people.find((p) => p.id === a)!,
    q = people.find((p) => p.id === b)!;
  const shared = p.interests.filter((s) =>
    q.interests.some((t) => t.label === s.label),
  );
  const t = p.interests[0].label.toLowerCase(),
    u = q.interests[0].label.toLowerCase(),
    scenario = curveballFor(a, b);
  const aScore = Math.min(
    96,
    scoreCandidate(p, q).score + 7 + (pairHash(a, b) % 9),
  );
  const bScore = Math.min(
    95,
    scoreCandidate(q, p).score + 3 + (pairHash(a, b) % 7),
  );
  const openings = [
    `Your card mentions ${u}. What's the part you could talk about for hours?`,
    `Okay, I have to ask about ${u}. Is that a weekend thing or an every-free-minute thing?`,
    `Before we do awkward small talk: what got you interested in ${u}?`,
  ];
  const answers = [
    `The best part is getting curious about a tiny detail. I could ask you the same about ${t}.`,
    `It started as a small interest and took over a corner of my weekends. How does ${t} fit into yours?`,
    `I like that there's always something new to notice. I get the feeling ${t} does that for you, too.`,
  ];
  const twists = [
    `I'd leave room for a detour. Maybe work ${t} into the plan without making it a whole production. What would you choose?`,
    `My vote: keep it low pressure, find something connected to ${t}, and let the rest unfold. Your move.`,
    `I'd start with something simple. Could we make a small ${t} experiment out of it?`,
  ];
  const finishes = [
    `Let's make it a collaboration: a little ${u}, a little of your idea. No spreadsheet required.`,
    `I can work with that. A little ${u} and permission to change the plan sounds pretty good.`,
    `Deal. I'll bring the ${u} idea if you promise we don't have to be good at it on the first try.`,
  ];
  return {
    id: `date-${String(index + 1).padStart(2, "0")}`,
    participantIds: [a, b],
    round,
    curveball: scenario,
    mode: "fixture",
    createdAt: "2026-10-04T09:00:00.000Z",
    messages: [
      {
        agentId: a,
        message: openings[index % 3],
        publicConfessional:
          "Good questions beat a rehearsed opening every time.",
        engagementDelta: 4,
      },
      {
        agentId: b,
        message: answers[index % 3],
        publicConfessional: shared.length
          ? "There is a shared thread here. I want to pull on it."
          : "Different interests. I like having something new to ask about.",
        engagementDelta: 5,
      },
      {
        agentId: a,
        message: twists[index % 3],
        publicConfessional:
          "The scenario makes the conversation a little less predictable.",
        engagementDelta: 6,
      },
      {
        agentId: b,
        message: finishes[index % 3],
        publicConfessional: "We found a plan with room for both of us.",
        engagementDelta: 7,
      },
    ],
    outcomes: [
      {
        agentId: a,
        candidateId: b,
        score: aScore,
        wantsAnotherDate: aScore >= 72,
        summary:
          aScore >= 80
            ? "I would absolutely keep talking."
            : "Good energy. I want to explore the different pace.",
      },
      {
        agentId: b,
        candidateId: a,
        score: bScore,
        wantsAnotherDate: bScore >= 72,
        summary:
          bScore >= 80
            ? "A different perspective, in the best way."
            : "An interesting conversation. A little more time would help.",
      },
    ],
  };
});
const data: DemoData = {
  version: 1,
  disclosure:
    "25 fictional adults. Authored source fixtures and precomputed simulations. No real profiles were scraped for this demo.",
  people,
  dates,
  rankings: rankAll(people, dates),
};
mkdirSync("src/data", { recursive: true });
writeFileSync("src/data/demo.generated.json", JSON.stringify(data));
console.log(
  `Generated ${people.length} fictional agents, ${dates.length} dates, ${Object.values(data.rankings).reduce((s, r) => s + r.length, 0)} directional rankings.`,
);
